version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 3.0.0
    - 3.0.1
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 3.1.3
    - 3.2.0
  - dependency-name: gatsby-remark-images
    versions:
    - 4.0.0
    - 4.1.0
    - 4.1.1
    - 4.2.0
  - dependency-name: gatsby-source-filesystem
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
  - dependency-name: gatsby-plugin-typescript
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
  - dependency-name: gatsby-remark-prismjs
    versions:
    - 4.0.0
    - 4.1.0
    - 4.2.0
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
  - dependency-name: gatsby-remark-autolink-headers
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
  - dependency-name: gatsby-remark-copy-linked-files
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
  - dependency-name: gatsby-remark-smartypants
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
  - dependency-name: gatsby-remark-responsive-iframe
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
  - dependency-name: gatsby-plugin-sitemap
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
  - dependency-name: gatsby-image
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 6.0.0
  - dependency-name: gatsby-plugin-emotion
    versions:
    - 6.0.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
  - dependency-name: gatsby-plugin-sass
    versions:
    - 3.2.0
