version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  build:
    commands:
      - npm run build
      #- npm run test:coverage
    finally:
      - npm prune
  post_build:
    commands:
      - npm run deploy

#artifacts:
#  files:
#    - "**/*"
#  base-directory: "public"
# remove 'build/' prefix from output files
# discard-paths: yes

cache:
  paths:
    - node_modules/**/*
