version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
      - curl -s -o mime.types "https://svn.apache.org/viewvc/httpd/httpd/trunk/docs/conf/mime.types?view=co"
      - sudo mv mime.types /etc/
  build:
    commands:
      - npm run build
      #- npm run test:coverage
    finally:
      - npm prune
  post_build:
    commands:
      - aws s3 sync --delete public "s3://www.robertsmieja.com/"

artifacts:
  files:
    - "**/*"
  base-directory: "public"
  # remove 'build/' prefix from output files
  # discard-paths: yes

cache:
  paths:
    - node_modules/**/*
