name: Publish

on:
  workflow_run:
    workflows: ["Node.js CI"]
    branches: 
      - master
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Setup PNPM
      uses: pnpm/action-setup@v4
      with:
        version: 10
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'pnpm'
    - run: pnpm config set ignore-scripts false
    - run: pnpm install
    - run: pnpm run --if-present build 
    - name: Publish to S3 Bucket
      run: |
        cd public/
        aws s3 sync . s3://www.robertsmieja.com --acl public-read --delete
